### ISSUE TITLE
Exception while processing a repository with SCSS files

### ISSUE THREAD

**Issue by c2v4** [anmol098/waka-readme-stats#102]
**Describe the bug**
Cannot process the repository with SCSS files used

**To Reproduce**
1. Have a project with SCSS files
2. Take a look at the processing logs

**Expected behavior**
Stats are being populated correctly

**Github repository link**
https://github.com/c2v4/c2v4

**Additional context**
Stacktrace:
`Traceback (most recent call last):
  File "/main.py", line 504, in <module>
    waka_stats = get_stats(g)
c2v4
Exception Occurred 'SCSS'
  File "/main.py", line 462, in get_stats
    loc.calculateLoc()
  File "/loc.py", line 33, in calculateLoc
    graph_file = graph.build_graph()
  File "/make_bar_graph.py", line 43, in build_graph
    if colors[language]['color'] is not None:
KeyError: 'SCSS'`

Probably function get() should be used to safely retrieve the value from the dictionary, as well as check for its result if its present before accessing ['color'].

**Comment by c2v4** [comment]
Can be solved temporarily by adding SCSS:
https://github.com/anmol098/waka-readme-stats/pull/103
