### ISSUE TITLE
BUG:  Exception Occurred No objects to concatenate:

### ISSUE THREAD

**Issue by sunnydanu** [anmol098/waka-readme-stats#173]
**Describe the bug**
Failed to update readme with exception " Exception Occurred No objects to concatenate

**To Reproduce**
1. Go to update_state.yml
2. don't set SHOW_LOC_CHART [which is true by default]
3. run workflow

![image](https://user-images.githubusercontent.com/48156739/110486938-20d31c00-8113-11eb-9b08-5fb52e6ac1e1.png)

**Expected behavior**
should be update readme 

**Github repository link**
https://github.com/sunnydanu/sunnydanu

**Additional context**
But if I set flag to false  SHOW_LOC_CHART . everything works fine.

detail logs

[logs_52.zip](https://github.com/anmol098/waka-readme-stats/files/6109204/logs_52.zip)

**Comment by aravindvnair99** [comment]
@sunnydanu Can you provide the link to your failed action run?

**Comment by sunnydanu** [comment]
> @sunnydanu Can you provide the link to your failed action run?
 Hi, @anmol098  here is the link [](https://github.com/sunnydanu/sunnydanu/runs/2079129091?check_suite_focus=true)

**Comment by aravindvnair99** [comment]
> > @sunnydanu Can you provide the link to your failed action run?
> > Hi, @anmol098  here is the [link ](https://github.com/sunnydanu/sunnydanu/runs/2079129091?check_suite_focus=true),
> 
> And it's show 0 line of code. even when run is success [with SHOW_LOC_CHART = false ] .
> 
> Thanks

Hey @sunnydanu ! I'm not @anmol098... But anyways, can you retry because for me it works without specifying `SHOW_LOC_CHART`.

**Comment by sunnydanu** [comment]
> > > @sunnydanu Can you provide the link to your failed action run?
> > > Hi, @anmol098  here is the [link ](https://github.com/sunnydanu/sunnydanu/runs/2079129091?check_suite_focus=true),
> > 
> > 
> > And it's show 0 line of code. even when run is success [with SHOW_LOC_CHART = false ] .
> > Thanks
> 
> Hey @sunnydanu ! I'm not @anmol098... But anyways, can you retry because for me it works without specifying `SHOW_LOC_CHART`.

**Comment by sunnydanu** [comment]
Hey @aravindvnair99 sorry my bad..  about workflow still not working. Do i need premium plan  at waka ? . My waka dashboard has all the changes but not updating readme . Still showing. 0 line of code . And  that exceptional is still here

**Comment by sunnydanu** [comment]
my waka dashboard 
![image](https://user-images.githubusercontent.com/48156739/110809218-b2c15d00-82aa-11eb-939f-3e00c42b053a.png)

**Comment by aravindvnair99** [comment]
> Hey @aravindvnair99 sorry my bad.. about workflow still not working. Do i need premium plan at waka ? . My waka dashboard has all the changes but not updating readme . Still showing. 0 line of code . And that exceptional is still here

@sunnydanu No, you don't need a premium account. The free one will do. Have you added the Wakatime API key to your repo?

Like this:

![image](https://user-images.githubusercontent.com/22199259/110809745-32e7c280-82ab-11eb-837f-ffee7caad886.png)

**Comment by aravindvnair99** [comment]
> my waka dashboard

@sunnydanu Can you share a screenshot of https://github.com/sunnydanu/sunnydanu/settings/secrets/actions?

**Comment by sunnydanu** [comment]
> > my waka dashboard
> 
> @sunnydanu Can you share a screenshot of https://github.com/sunnydanu/sunnydanu/settings/secrets/actions?

![image](https://user-images.githubusercontent.com/48156739/110818733-8cec8600-82b3-11eb-8ea1-3b5e0f1455c3.png)

**Comment by aravindvnair99** [comment]
> > > my waka dashboard
> > 
> > 
> > @sunnydanu Can you share a screenshot of https://github.com/sunnydanu/sunnydanu/settings/secrets/actions?
> 

@sunnydanu you sure you have entered your API key correctly? Can you re-enter and check if the issue still exists?

**Comment by sunnydanu** [comment]
@aravindvnair99  updates. still having same issue.

**Comment by aravindvnair99** [comment]
> @aravindvnair99 updated. still having same issue.

@sunnydanu Go to https://github.com/settings/tokens, select the token you made and attach the screenshot here of what options are ticked there.

**Comment by sunnydanu** [comment]
@aravindvnair99 
![image](https://user-images.githubusercontent.com/48156739/110870386-55e99500-82f2-11eb-860e-ebc8563eb4d6.png)

**Comment by sunnydanu** [comment]
is anyone looking this ..? I really need to keep this work .

**Comment by sunnydanu** [comment]
Hey @aravindvnair99  I found a reason . behind this unexpected behavior . the reason was I don't have any public repo over here which I owned. so as I push one public repo. it worked,  so that was the issue .

But still it's should not break the flow. rather then skip .. you guys know better how to that in python.

**Comment by aravindvnair99** [comment]
> Hey @aravindvnair99 I found a reason . behind this unexpected behavior . the reason was I don't have any public repo over here which I owned [recently removed last one]. so as I push one public repo. it worked and that's it.
> 
> But still it's should not break the flow. rather then skip ..
> 
> Thanks

@sunnydanu Ah nice catch! But that's not the reason. You do have public repositories. It didn't work because the languages used couldn't be identified. The only public repository you had contributed to was https://github.com/sunnydanu/sunnydanu which is just text files. Whereas when you added some JavaScript code, it started working:

![image](https://user-images.githubusercontent.com/22199259/111038993-bc38f980-8451-11eb-93d5-ec965f29540e.png)

@anmol098 We have a confirmed bug here although only those with code should use the stats. xP

**Comment by sunnydanu** [comment]
@anmol098  ahh. Now things getting clear to me. I had few public repos earlier when I first use waka-state so it worked.  after that I deleted my repos. and got stucked.... LOL took me while to figure out .. So I post it here. 
Thanks for your updates though I have one question. my line of code is show 3. But my nodejs-demo has more then 3 words. [https://github.com/sunnydanu/nodejs-demo/commits/master](https://github.com/sunnydanu/nodejs-demo/commits/master) 

how dose it count ? 

thanks

**Comment by aravindvnair99** [comment]
> @anmol098 ahh. Now things getting clear to me. I had few public repos earlier when I first use waka-state so it worked. after that I deleted my repos. and got stucked.... LOL took me while to figure out .. So I post it here.
> Thanks for your updates though I have one question. my line of code is show 3. But my nodejs-demo has more then 3 words. https://github.com/sunnydanu/nodejs-demo/commits/master
> 
> how dose it count ?
> 
> thanks

@sunnydanu Refer these:

- https://github.com/anmol098/waka-readme-stats/blob/fda9fd3bb5626c4ac4632fd23a1d5349f67ff500/main.py#L438-L441
- https://github.com/anmol098/waka-readme-stats/blob/fda9fd3bb5626c4ac4632fd23a1d5349f67ff500/main.py#L385-L390
- https://github.com/anmol098/waka-readme-stats/blob/fda9fd3bb5626c4ac4632fd23a1d5349f67ff500/loc.py#L1-L106

**Comment by sunnydanu** [comment]
Hi @aravindvnair99  my profile status are not updating. can you help me with that. it's in waka dashboard but not updating my readme file. line of code. anything.

**Comment by aravindvnair99** [comment]
> Hi @aravindvnair99 my profile status are not updating. can you help me with that. it's in waka dashboard but not updating my readme file. line of code. anything.

@sunnydanu Delete this: https://github.com/sunnydanu/sunnydanu/blob/master/charts/bar_graph.png and run the workflow. See what happens.

**Comment by Dieman89** [comment]
Hello, I am having the exact same problem:

`Traceback (most recent call last):
Username Dieman89
  File "/main.py", line 502, in <module>
Exception Occurred 'NoneType' object is not subscriptable
    waka_stats = get_stats(g)
  File "/main.py", line 450, in get_stats
    stats += get_waka_time_stats()
  File "/main.py", line 305, in get_waka_time_stats
    stats = stats + generate_commit_list(tz=data['data']['timezone']) + '\n\n'
  File "/main.py", line 196, in generate_commit_list
    repos = [d for d in nodes if d['isFork'] is False]
  File "/main.py", line 196, in <listcomp>
    repos = [d for d in nodes if d['isFork'] is False]
TypeError: 'NoneType' object is not subscriptable`

**Comment by aravindvnair99** [comment]
> Hello, I am having the exact same problem:
> 
> `Traceback (most recent call last): Username Dieman89 File "/main.py", line 502, in <module> Exception Occurred 'NoneType' object is not subscriptable waka_stats = get_stats(g) File "/main.py", line 450, in get_stats stats += get_waka_time_stats() File "/main.py", line 305, in get_waka_time_stats stats = stats + generate_commit_list(tz=data['data']['timezone']) + '\n\n' File "/main.py", line 196, in generate_commit_list repos = [d for d in nodes if d['isFork'] is False] File "/main.py", line 196, in <listcomp> repos = [d for d in nodes if d['isFork'] is False] TypeError: 'NoneType' object is not subscriptable`

@Dieman89 Did you give correct access for the GitHub token?

**Comment by Dieman89** [comment]
Yea, repo and user. > > Hello, I am having the exact same problem:
> 
> > 
> 
> > `Traceback (most recent call last): Username Dieman89 File "/main.py", line 502, in <module> Exception Occurred 'NoneType' object is not subscriptable waka_stats = get_stats(g) File "/main.py", line 450, in get_stats stats += get_waka_time_stats() File "/main.py", line 305, in get_waka_time_stats stats = stats + generate_commit_list(tz=data['data']['timezone']) + '\n\n' File "/main.py", line 196, in generate_commit_list repos = [d for d in nodes if d['isFork'] is False] File "/main.py", line 196, in <listcomp> repos = [d for d in nodes if d['isFork'] is False] TypeError: 'NoneType' object is not subscriptable`
> 
> 
> 
> @Dieman89 Did you give correct access for the GitHub token?

**Comment by aravindvnair99** [comment]
> Yea, repo and user.

@Dieman89 I've sent you a [PR](https://github.com/Dieman89/Dieman89/pull/1). Merge and check if that helps.

**Comment by Dieman89** [comment]
> > Yea, repo and user.
> 
> @Dieman89 I've sent you a [PR](https://github.com/Dieman89/Dieman89/pull/1). Merge and check if that helps.

Same error:

`Username Dieman89
Traceback (most recent call last):
  File "/main.py", line 502, in <module>
Exception Occurred 'NoneType' object is not subscriptable
    waka_stats = get_stats(g)
  File "/main.py", line 450, in get_stats
    stats += get_waka_time_stats()
  File "/main.py", line 305, in get_waka_time_stats
    stats = stats + generate_commit_list(tz=data['data']['timezone']) + '\n\n'
  File "/main.py", line 196, in generate_commit_list
    repos = [d for d in nodes if d['isFork'] is False]
  File "/main.py", line 196, in <listcomp>
    repos = [d for d in nodes if d['isFork'] is False]
TypeError: 'NoneType' object is not subscriptable`

**Comment by Dieman89** [comment]
@aravindvnair99 any idea?

**Comment by sunnydanu** [comment]
any fix.?? still line of code is stuck in 3. :-/
