### ISSUE TITLE
BUG: KeyError: 'Handlebars'

### ISSUE THREAD

**Issue by deadshot674gam** [anmol098/waka-readme-stats#182]
Traceback (most recent call last):
deadshot674gam
  File "/main.py", line 498, in <module>
Please add new github personal access token with user permission
    waka_stats = get_stats(g)
  File "/main.py", line 455, in get_stats
    loc.plotLoc(yearly_data)
  File "/loc.py", line 36, in plotLoc
    graph.build_graph()
  File "/make_bar_graph.py", line 43, in build_graph
    if colors[language]['color'] is not None:
KeyError: 'Handlebars'

**Comment by deadshot674gam** [comment]
Solved it in the colors.json file
