### ISSUE TITLE
BUG Exception Occurred 'languages'

### ISSUE THREAD

**Issue by coldnight** [anmol098/waka-readme-stats#222]
**Describe the bug**
```
Username coldnight
  File "/main.py", line 511, in <module>
    waka_stats = get_stats(g)
  File "/main.py", line 456, in get_stats
    stats += get_waka_time_stats()
  File "/main.py", line 318, in get_waka_time_stats
    if len(data['data']['languages']) == 0:
KeyError: 'languages'
Exception Occurred 'languages'
```

**Github repository link**
https://github.com/coldnight/coldnight

**Additional context**

**Comment by umang-sinha** [comment]
I've been encountering the same issue. The workflows run as scheduled but the README file does not get updated with the recent data.

``` Username umang-sinha
Traceback (most recent call last):
  File "/main.py", line 511, in <module>
    waka_stats = get_stats(g)
  File "/main.py", line 456, in get_stats
    stats += get_waka_time_stats()
  File "/main.py", line 318, in get_waka_time_stats
    if len(data['data']['languages']) == 0:
KeyError: 'languages'
Exception Occurred 'languages'

**Comment by anmol098** [comment]
@coldnight  as I can see in your profile the latest updates and the action is working fine so closing this as of now

**Comment by Abvent-Jonathan** [comment]
I have the same problem, the workflow runs fine every day, and the last update commit was 8 days ago.

```
 Traceback (most recent call last):
Username jdebetaz
Exception Occurred 'languages'
  File "/main.py", line 515, in <module>
    waka_stats = get_stats(g)
  File "/main.py", line 458, in get_stats
    stats += get_waka_time_stats()
  File "/main.py", line 320, in get_waka_time_stats
    if len(data['data']['languages']) == 0:
KeyError: 'languages'
```

There is [my repository ](https://github.com/jdebetaz/jdebetaz)

**Comment by jdebetaz** [comment]
I have the same problem, the workflow runs well every day, and the last update commit was 8 days ago.

```
 Traceback (most recent call last):
Username jdebetaz
Exception Occurred 'languages'
  File "/main.py", line 515, in <module>
    waka_stats = get_stats(g)
  File "/main.py", line 458, in get_stats
    stats += get_waka_time_stats()
  File "/main.py", line 320, in get_waka_time_stats
    if len(data['data']['languages']) == 0:
KeyError: 'languages'
```

There is [my repository](https://github.com/jdebetaz/jdebetaz)
