### ISSUE TITLE
BUG Exception Occurred list 'index out of range'

### ISSUE THREAD

**Issue by GoogolDKhan** [anmol098/waka-readme-stats#223]
**Describe the bug**
```
Username GoogolDKhan
Exception Occurred list index out of range
Traceback (most recent call last):
  File "/main.py", line 511, in <module>
    waka_stats = get_stats(g)
  File "/main.py", line 453, in get_stats
    stats += get_short_info(github)
  File "/main.py", line 411, in get_short_info
    total = data['years'][0]['total']
IndexError: list index out of range
```

**Github repository link**
https://github.com/GoogolDKhan/GoogolDKhan

**Comment by GoogolDKhan** [comment]
It working perfectly now.
