### ISSUE TITLE
KeyError: 'text'

### ISSUE THREAD

**Issue by Arondight** [anmol098/waka-readme-stats#243]
**Describe the bug**

The data has not been updated for several days, also graphs `charts/bar_graph.png`.

**To Reproduce**

**Expected behavior**

**Github repository link**

https://github.com/Arondight/Arondight

**Additional context**

```
2021-12-03T20:03:19.2091981Z npm does not support Node.js v15.14.0
2021-12-03T20:03:19.2093217Z You should probably upgrade to a newer version of node as we
2021-12-03T20:03:19.2095646Z can't make any promises that npm will work with this version.
2021-12-03T20:03:19.2096679Z You can find the latest version at https://nodejs.org/
2021-12-03T20:03:19.5006381Z npm does not support Node.js v15.14.0
2021-12-03T20:03:19.5007439Z You should probably upgrade to a newer version of node as we
2021-12-03T20:03:19.5008829Z can't make any promises that npm will work with this version.
2021-12-03T20:03:19.5009885Z You can find the latest version at https://nodejs.org/
2021-12-03T20:03:20.8154274Z Traceback (most recent call last):
2021-12-03T20:03:20.8154857Z   File "/main.py", line 548, in <module>
2021-12-03T20:03:20.8155533Z     waka_stats = get_stats(g)
2021-12-03T20:03:20.8155979Z   File "/main.py", line 476, in get_stats
2021-12-03T20:03:20.8157035Z     data['data']['text'])) + '-blue)\n\n'
2021-12-03T20:03:20.8157558Z KeyError: 'text'
2021-12-03T20:03:20.8157973Z Username Arondight
2021-12-03T20:03:20.8158518Z Exception Occurred 'text'
2021-12-03T20:03:21.0612325Z Cleaning up orphan processes
```

**Comment by Arondight** [comment]
Nothing changed in my repo.

![图片](https://user-images.githubusercontent.com/13673702/144734867-6d3e5d08-b24f-4f51-a74e-fec9af6f345c.png)

**Comment by mheob** [comment]
Yes. Same for me. See my [Action output](https://github.com/mheob/mheob/runs/4420144906)

```text
Run anmol098/waka-readme-stats@master
  with:
    GH_TOKEN: ***
    WAKATIME_API_KEY: ***
    SHOW_OS: true
    SHOW_PROJECTS: true
    SHOW_EDITORS: true
    SHOW_TIMEZONE: true
    SHOW_COMMIT: true
    SHOW_LANGUAGE: true
    SHOW_LINES_OF_CODE: true
    SHOW_LANGUAGE_PER_REPO: true
    SHOW_LOC_CHART: false
    SHOW_DAYS_OF_WEEK: true
    SHOW_PROFILE_VIEWS: true
    SHOW_SHORT_INFO: false
    LOCALE: en
    SHOW_TOTAL_CODE_TIME: true
    COMMIT_BY_ME: true
    COMMIT_MESSAGE: Updated with Dev Metrics
    SHOW_UPDATED_DATE: True
/usr/bin/docker run --name b62bc446fc5944442bb96897c9c51bb8b10_36bf20 --label 905b62 --workdir /github/workspace --rm -e INPUT_GH_TOKEN -e INPUT_WAKATIME_API_KEY -e INPUT_SHOW_OS -e INPUT_SHOW_PROJECTS -e INPUT_SHOW_EDITORS -e INPUT_SHOW_TIMEZONE -e INPUT_SHOW_COMMIT -e INPUT_SHOW_LANGUAGE -e INPUT_SHOW_LINES_OF_CODE -e INPUT_SHOW_LANGUAGE_PER_REPO -e INPUT_SHOW_LOC_CHART -e INPUT_SHOW_DAYS_OF_WEEK -e INPUT_SHOW_PROFILE_VIEWS -e INPUT_SHOW_SHORT_INFO -e INPUT_LOCALE -e INPUT_SHOW_TOTAL_CODE_TIME -e INPUT_COMMIT_BY_ME -e INPUT_IGNORED_REPOS -e INPUT_COMMIT_MESSAGE -e INPUT_SHOW_UPDATED_DATE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/mheob/mheob":"/github/workspace" 905b62:bc446fc5944442bb96897c9c51bb8b10
Traceback (most recent call last):
Username mheob
Exception Occurred 'text'
  File "/main.py", line 548, in <module>
    waka_stats = get_stats(g)
  File "/main.py", line 476, in get_stats
    data['data']['text'])) + '-blue)\n\n'
KeyError: 'text'
```

**Comment by Prathamesh-B** [comment]
#### I don't think `show_total_code_time` is working for everyone right now.
> My API response ⬇️
![image](https://user-images.githubusercontent.com/55992548/144741528-dd22bd90-eb5c-4420-9d31-42fb26301821.png)

### A simple fix if you are getting this error
> make SHOW_TOTAL_CODE_TIME  to Flase in the Workflow File:
```yml 
- uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TOTAL_CODE_TIME: "Flase"
```

**Comment by mheob** [comment]
You are right.

Quick Typo Fix: 

> ```yaml
> […]
>           SHOW_TOTAL_CODE_TIME: "Flase"
> ```

should be 

```yaml
         SHOW_TOTAL_CODE_TIME: "False"
 ```

**Comment by Arondight** [comment]
@anmol098 Hello, can you do a fix? I think this case should handle by the code rather than users

**Comment by anmol098** [comment]
Yes i will deploy the fix.. I was not aware of varying response from the
Waka api
