### ISSUE TITLE
BUG KeyError: 'languages'

### ISSUE THREAD

**Issue by ChesterYue** [anmol098/waka-readme-stats#252]
bug shown from about 2021-12-19

**Describe the bug**
```
Traceback (most recent call last):
Username ChesterYue
  File "/main.py", line 553, in <module>
User stats are calculating. Try again later.
    waka_stats = get_stats(g)
Exception Occurred 'languages'
  File "/main.py", line 497, in get_stats
    stats += get_waka_time_stats()
  File "/main.py", line 333, in get_waka_time_stats
    if len(data['data']['languages']) == 0:
KeyError: 'languages'
```
<img width="1602" alt="Screen Shot 2022-01-05 at 5 39 53 PM" src="https://user-images.githubusercontent.com/8273263/148197131-e0021069-4d20-4440-acd6-d944b3566efc.png">

**Comment by ChesterYue** [comment]
`brew info wakatime-cli`

```
wakatime-cli: stable 1.32.1 (bottled)
Command-line interface to the WakaTime api
https://wakatime.com/
/usr/local/Cellar/wakatime-cli/1.32.1 (6 files, 16.4MB) *
  Poured from bottle on 2022-01-05 at 11:05:29
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/wakatime-cli.rb
License: BSD-3-Clause
==> Dependencies
Build: go ✔
==> Analytics
install: 461 (30 days), 985 (90 days), 1,256 (365 days)
install-on-request: 460 (30 days), 985 (90 days), 1,258 (365 days)
build-error: 0 (30 days)
```

**Comment by ChesterYue** [comment]
github token issue
