### ISSUE TITLE
BUG Connection reset by peer

### ISSUE THREAD

**Issue by Arondight** [anmol098/waka-readme-stats#261]
**Describe the bug**
```
2022-02-03T20:03:18.8239776Z npm does not support Node.js v15.14.0
2022-02-03T20:03:18.8240250Z You should probably upgrade to a newer version of node as we
2022-02-03T20:03:18.8240999Z can't make any promises that npm will work with this version.
2022-02-03T20:03:18.8241401Z You can find the latest version at https://nodejs.org/
2022-02-03T20:03:19.1594433Z npm does not support Node.js v15.14.0
2022-02-03T20:03:19.1594849Z You should probably upgrade to a newer version of node as we
2022-02-03T20:03:19.1595581Z can't make any promises that npm will work with this version.
2022-02-03T20:03:19.1595997Z You can find the latest version at https://nodejs.org/
2022-02-03T20:05:27.6688233Z Traceback (most recent call last):
2022-02-03T20:05:27.6688565Z Username Arondight
2022-02-03T20:05:27.6690531Z   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
2022-02-03T20:05:27.6690996Z User stats are calculating. Try again later.
2022-02-03T20:05:27.6691677Z Exception Occurred ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2022-02-03T20:05:27.6756138Z     httplib_response = self._make_request(
2022-02-03T20:05:27.6757193Z   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
2022-02-03T20:05:27.6757728Z     self._validate_conn(conn)
2022-02-03T20:05:27.6758306Z   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
2022-02-03T20:05:27.6758692Z     conn.connect()
2022-02-03T20:05:27.6804234Z   File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
2022-02-03T20:05:27.6804669Z     self.sock = ssl_wrap_socket(
2022-02-03T20:05:27.6805214Z   File "/usr/local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
2022-02-03T20:05:27.6805614Z     ssl_sock = _ssl_wrap_socket_impl(
2022-02-03T20:05:27.6806435Z   File "/usr/local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
2022-02-03T20:05:27.6806905Z     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
2022-02-03T20:05:27.6807325Z   File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket
2022-02-03T20:05:27.6807659Z     return self.sslsocket_class._create(
2022-02-03T20:05:27.6808013Z   File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create
2022-02-03T20:05:27.6808331Z     self.do_handshake()
2022-02-03T20:05:27.6808666Z   File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake
2022-02-03T20:05:27.6809042Z     self._sslobj.do_handshake()
2022-02-03T20:05:27.6809396Z ConnectionResetError: [Errno 104] Connection reset by peer
2022-02-03T20:05:27.6809623Z 
2022-02-03T20:05:27.6809822Z During handling of the above exception, another exception occurred:
2022-02-03T20:05:27.6810062Z 
2022-02-03T20:05:27.6810191Z Traceback (most recent call last):
2022-02-03T20:05:27.6810699Z   File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
2022-02-03T20:05:27.6811069Z     resp = conn.urlopen(
2022-02-03T20:05:27.6811595Z   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
2022-02-03T20:05:27.6811976Z     retries = retries.increment(
2022-02-03T20:05:27.6812497Z   File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 532, in increment
2022-02-03T20:05:27.6812918Z     raise six.reraise(type(error), error, _stacktrace)
2022-02-03T20:05:27.6813463Z   File "/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
2022-02-03T20:05:27.6813830Z     raise value.with_traceback(tb)
2022-02-03T20:05:27.6814354Z   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
2022-02-03T20:05:27.6814756Z     httplib_response = self._make_request(
2022-02-03T20:05:27.6815296Z   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
2022-02-03T20:05:27.6815683Z     self._validate_conn(conn)
2022-02-03T20:05:27.6816218Z   File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
2022-02-03T20:05:27.6816591Z     conn.connect()
2022-02-03T20:05:27.6817071Z   File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
2022-02-03T20:05:27.6817438Z     self.sock = ssl_wrap_socket(
2022-02-03T20:05:27.6817965Z   File "/usr/local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
2022-02-03T20:05:27.6818338Z     ssl_sock = _ssl_wrap_socket_impl(
2022-02-03T20:05:27.6818877Z   File "/usr/local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
2022-02-03T20:05:27.6819336Z     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
2022-02-03T20:05:27.6819740Z   File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket
2022-02-03T20:05:27.6820262Z     return self.sslsocket_class._create(
2022-02-03T20:05:27.6820709Z   File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create
2022-02-03T20:05:27.6821146Z     self.do_handshake()
2022-02-03T20:05:27.6821507Z   File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake
2022-02-03T20:05:27.6822059Z     self._sslobj.do_handshake()
2022-02-03T20:05:27.6822836Z urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2022-02-03T20:05:27.6823228Z 
2022-02-03T20:05:27.6823465Z During handling of the above exception, another exception occurred:
2022-02-03T20:05:27.6824205Z 
2022-02-03T20:05:27.6824337Z Traceback (most recent call last):
2022-02-03T20:05:27.6824730Z   File "/main.py", line 553, in <module>
2022-02-03T20:05:27.6825192Z     waka_stats = get_stats(g)
2022-02-03T20:05:27.6825598Z   File "/main.py", line 494, in get_stats
2022-02-03T20:05:27.6825921Z     stats += get_short_info(github)
2022-02-03T20:05:27.6826452Z   File "/main.py", line 432, in get_short_info
2022-02-03T20:05:27.6827157Z     request = requests.get('https://github-contributions.now.sh/api/v1/' + user_info.login)
2022-02-03T20:05:27.6827862Z   File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 76, in get
2022-02-03T20:05:27.6828448Z     return request('get', url, params=params, **kwargs)
2022-02-03T20:05:27.6829060Z   File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
2022-02-03T20:05:27.6829572Z     return session.request(method=method, url=url, **kwargs)
2022-02-03T20:05:27.6830155Z   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
2022-02-03T20:05:27.6830732Z     resp = self.send(prep, **send_kwargs)
2022-02-03T20:05:27.6831334Z   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 677, in send
2022-02-03T20:05:27.6831799Z     history = [resp for resp in gen]
2022-02-03T20:05:27.6832343Z   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 677, in <listcomp>
2022-02-03T20:05:27.6832870Z     history = [resp for resp in gen]
2022-02-03T20:05:27.6833501Z   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 237, in resolve_redirects
2022-02-03T20:05:27.6833962Z     resp = self.send(
2022-02-03T20:05:27.6834484Z   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
2022-02-03T20:05:27.6834973Z     r = adapter.send(request, **kwargs)
2022-02-03T20:05:27.6835608Z   File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
2022-02-03T20:05:27.6836044Z     raise ConnectionError(err, request=request)
2022-02-03T20:05:27.6836770Z requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2022-02-03T20:05:28.0673009Z Cleaning up orphan processes
```

**To Reproduce**

**Expected behavior**

**Github repository link**
https://github.com/Arondight/Arondight

**Additional context**

**Comment by Arondight** [comment]
you can check my repo's action output

**Comment by aravindvnair99** [comment]
@Arondight Duplicate of #258

**Comment by Arondight** [comment]
thanks
