### ISSUE TITLE
BUG Not updating

### ISSUE THREAD

**Issue by modem7** [anmol098/waka-readme-stats#310]
```
Traceback (most recent call last):
  File "/main.py", line 561, in <module>
    waka_stats = get_stats(g)
  File "/main.py", line 506, in get_stats
    stats += get_waka_time_stats()
  File "/main.py", line [34](https://github.com/modem7/modem7/runs/7668866283?check_suite_focus=true#step:3:35)5, in get_waka_time_stats
    if len(data['data']['languages']) == 0:
KeyError: 'languages'
Username modem7
Exception Occurred 'languages'
```

Waka.yml
```yaml
name: Waka Readme

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_LOC_CHART: "False"
          LOCALE: "en"
```

**Comment by modem7** [comment]
Seems to work if I update with `SHOW_TOTAL_CODE_TIME: "False"`.

Possibly related to https://github.com/anmol098/waka-readme-stats/issues/309

**Comment by thenithinbalaji** [comment]
It also works when WAKATIME API KEY is removed from with: in the yml file

**Comment by modem7** [comment]
Looks like the issue has come back, regardless of adding/removing variables.

**Comment by laureanray** [comment]
I am also experiencing this one. Same with the above logs.

**Comment by modem7** [comment]
> I am also experiencing this one. Same with the above logs. Any workarounds @modem7?

Unfortunately nothing my end, we'll probably need the dev to have a look as it seems even his page isn't updating

**Comment by txtxj** [comment]
I have the same problem.

So I record the [json content](https://github.com/txtxj/txtxj/commit/2a5407273b313f89e537f069c1bef3110fd7be55?diff=split) that the script gets when the README update fails.

```
{"data":{"human_readable_range":"last week","is_already_updating":false,"is_coding_activity_visible":true,"is_including_today":false,"is_other_usage_visible":true,"is_stuck":false,"is_up_to_date":false,"is_up_to_date_pending_future":false,"percent_calculated":71,"range":"last_7_days","status":"pending_update","timeout":15,"timezone":"Asia/Shanghai","username":"txtxj","writes_only":false},"message":"Calculating stats for this user. Check back later."}
```

At the end of the json file, there is a message `Calculating stats for this user. Check back later.`

So it is the wakatime server that did not finish calculating the users' data for the day, not a problem with this repository's script.

Maybe you could run the code at another time?

**Comment by modem7** [comment]
> I have the same problem.
> 
> So I record the [json content](https://github.com/txtxj/txtxj/commit/2a5407273b313f89e537f069c1bef3110fd7be55?diff=split) that the script gets when the README update fails.
> 
> ```
> {"data":{"human_readable_range":"last week","is_already_updating":false,"is_coding_activity_visible":true,"is_including_today":false,"is_other_usage_visible":true,"is_stuck":false,"is_up_to_date":false,"is_up_to_date_pending_future":false,"percent_calculated":71,"range":"last_7_days","status":"pending_update","timeout":15,"timezone":"Asia/Shanghai","username":"txtxj","writes_only":false},"message":"Calculating stats for this user. Check back later."}
> ```
> 
> At the end of the json file, there is a message `Calculating stats for this user. Check back later.`
> 
> So it is the wakatime server that did not finish calculating the users' data for the day, not a problem with this repository's script.
> 
> Maybe you could run the code at another time?

That's the problem, it doesn't get to the waka server stage. I've had the issues w/ the waka server being overloaded before, but in this particular case, it's definitely something else.

This is my full output:

```
Run anmol098/waka-readme-stats@master
  with:
    WAKATIME_API_KEY: ***
    GH_TOKEN: ***
    SHOW_LINES_OF_CODE: False
    SHOW_PROFILE_VIEWS: False
    SHOW_LOC_CHART: False
    LOCALE: en
    SHOW_TOTAL_CODE_TIME: False
    SHOW_OS: True
    SHOW_PROJECTS: True
    SHOW_EDITORS: True
    SHOW_TIMEZONE: True
    SHOW_COMMIT: True
    SHOW_LANGUAGE: True
    SHOW_LANGUAGE_PER_REPO: True
    SHOW_DAYS_OF_WEEK: True
    SHOW_SHORT_INFO: True
    COMMIT_BY_ME: False
    COMMIT_MESSAGE: Updated with Dev Metrics
    SHOW_UPDATED_DATE: True
    UPDATED_DATE_FORMAT: %d/%m/%Y %H:%M:%S
    SYMBOL_VERSION: 1
/usr/bin/docker run --name b56cc98f061be4fe9855a674aa[2](https://github.com/modem7/modem7/runs/7858654117?check_suite_focus=true#step:3:2)591b89_9c0a45 --label 94859b --workdir /github/workspace --rm -e INPUT_WAKATIME_API_KEY -e INPUT_GH_TOKEN -e INPUT_SHOW_LINES_OF_CODE -e INPUT_SHOW_PROFILE_VIEWS -e INPUT_SHOW_LOC_CHART -e INPUT_LOCALE -e INPUT_SHOW_TOTAL_CODE_TIME -e INPUT_SHOW_OS -e INPUT_SHOW_PROJECTS -e INPUT_SHOW_EDITORS -e INPUT_SHOW_TIMEZONE -e INPUT_SHOW_COMMIT -e INPUT_SHOW_LANGUAGE -e INPUT_SHOW_LANGUAGE_PER_REPO -e INPUT_SHOW_DAYS_OF_WEEK -e INPUT_SHOW_SHORT_INFO -e INPUT_COMMIT_BY_ME -e INPUT_IGNORED_REPOS -e INPUT_COMMIT_MESSAGE -e INPUT_SHOW_UPDATED_DATE -e INPUT_UPDATED_DATE_FORMAT -e INPUT_SYMBOL_VERSION -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_TRIGGERING_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/modem7/modem7":"/github/workspace" 94859b:56cc98f061be4fe9855a674aa2591b89
Traceback (most recent call last):
  File "/main.py", line 561, in <module>
    waka_stats = get_stats(g)
  File "/main.py", line 506, in get_stats
    stats += get_waka_time_stats()
  File "/main.py", line [3](https://github.com/modem7/modem7/runs/7858654117?check_suite_focus=true#step:3:3)[4](https://github.com/modem7/modem7/runs/7858654117?check_suite_focus=true#step:3:4)[5](https://github.com/modem7/modem7/runs/7858654117?check_suite_focus=true#step:3:5), in get_waka_time_stats
    if len(data['data']['languages']) == 0:
KeyError: 'languages'
Username modem[7](https://github.com/modem7/modem7/runs/7858654117?check_suite_focus=true#step:3:7)
Exception Occurred 'languages'
```

**Comment by modem7** [comment]
Adding a cron that works for multiple times a day seems to work
