### ISSUE TITLE
BUG: KeyError: 'Vim Script'

### ISSUE THREAD

**Issue by tanjuntao** [anmol098/waka-readme-stats#322]
**Describe the bug**
'Vim Script' is not supported which causes a key error in `main.py`.  

**Bug details**
In the 3rd step of the GitHub Action job, I got the following error,
``` python
Traceback (most recent call last):
  File "/main.py", line 566, in <module>
    waka_stats = get_stats(g)
  File "/main.py", line 480, in get_stats
    yearly_data = get_yearly_data()
  File "/main.py", line 422, in get_yearly_data
    loc.plotLoc(yearly_data)
  File "/loc.py", line 38, in plotLoc
    graph.build_graph()
  File "/make_bar_graph.py", line 43, in build_graph
    if colors[language]['color'] is not None:
KeyError: 'Vim Script'
Username tanjuntao
Exception Occurred 'Vim Script'
```
which is obviously due to that 'Vim Script' language is not supported.

**Comment by deloz** [comment]
got the same error
