### ISSUE TITLE
BUG: `ZeroDivisionError: division by zero`

### ISSUE THREAD

**Issue by Searge** [anmol098/waka-readme-stats#323]
**Describe the bug**

Hello.
I use mostly the same config as you:
- https://github.com/Searge/Searge/blob/main/.github/workflows/wakatime.yml
- https://github.com/amomorning/amomorning/blob/main/.github/workflows/waka-readme.yml

All tokens are working, but action return next:

```sh
Traceback (most recent call last):
  File "/main.py", line 566, in <module>
    waka_stats = get_stats(g)
  File "/main.py", line 509, in get_stats
    stats += get_waka_time_stats()
  File "/main.py", line 336, in get_waka_time_stats
    stats = stats + generate_commit_list(tz=data['data']['timezone']) + '\n\n'
  File "/main.py", line 287, in generate_commit_list
    "percent": round((morning / sumAll) * 100, 2)},
ZeroDivisionError: division by zero
Username Searge
Exception occurred 'Europe/Kyiv'
...
Exception occurred 'Europe/Kyiv'
Exception Occurred division by zero
```
https://github.com/Searge/Searge/runs/8173361035?check_suite_focus=true#step:3:27

**GitHub repository link**
- [Actions](https://github.com/Searge/Searge/actions)

**Additional context**
It looks like a timezone issue, but I'm not sure.

**Comment by dividedby-0** [comment]
Getting the same exception:
```
Traceback (most recent call last):
  File "/main.py", line 566, in <module>
    waka_stats = get_stats(g)
  File "/main.py", line 509, in get_stats
    stats += get_waka_time_stats()
  File "/main.py", line 336, in get_waka_time_stats
    stats = stats + generate_commit_list(tz=data['data']['timezone']) + '\n\n'
  File "/main.py", line [28](https://github.com/dividedby-0/dividedby-0/actions/runs/3412566538/jobs/5678244205#step:3:29)7, in generate_commit_list
    "percent": round((morning / sumAll) * 100, 2)},
ZeroDivisionError: division by zero
Username dividedby-0
Exception occurred 'Europe/Kyiv'
Exception occurred 'Europe/Kyiv'
Exception occurred 'Europe/Kyiv'
Exception occurred 'Europe/Kyiv'
Exception occurred 'Europe/Kyiv'
Exception occurred 'Europe/Kyiv'
Exception occurred 'Europe/Kyiv'
Exception Occurred division by zero
```
However, switching the WakaTime timezone from Europe/Kyiv to Europe/Rome worked around the issue. AFAIK Kyiv timezone is GMT+2 while Rome timezone is GMT+1, maybe this could help?

**Comment by MarkenJaden** [comment]
Hey,

sorry no one has responded in so long.

The bug seems to be fixed by now, but if there are still problems please reopen the issue.
