### ISSUE TITLE
BUG | subprocess.CalledProcessError: Command '['/usr/bin/npm', 'bin', '--global']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by anoduck** [anmol098/waka-readme-stats#348]
Been working on this, recently updated my `GH_TOKEN` because I suspected it of creating the first set of errors that I encountered. 

```bash

Traceback (most recent call last):   File "/main.py", line 550, in <module>     user_data = run_query(userInfoQuery)  # Execute the query Exception Occurred Query failed to run by returning code of 401.  {     viewer {       login       email       id     }   }    File "/main.py", line 176, in run_query     raise Exception("Query failed to run by returning code of {}. {}".format(request.status_code, query)) Exception: Query failed to run by returning code of 401.  {     viewer {       login       email       id     }   }

```

But, after making this change, I ran the workflow again, and it appears to have exploded somehow.

```bash

Traceback (most recent call last):
  File "/main.py", line 566, in <module>
    waka_stats = get_stats(g)
  File "/main.py", line 480, in get_stats
    yearly_data = get_yearly_data()
  File "/main.py", line 422, in get_yearly_data
    loc.plotLoc(yearly_data)
  File "/loc.py", line 38, in plotLoc
    graph.build_graph()
  File "/make_bar_graph.py", line 105, in build_graph
    chart.save('bar_graph.png')
  File "/usr/local/lib/python3.9/site-packages/altair/vegalite/v4/api.py", line 476, in save
    result = save(**kwds)
  File "/usr/local/lib/python3.9/site-packages/altair/utils/save.py", line 112, in save
    mimebundle = spec_to_mimebundle(
  File "/usr/local/lib/python3.9/site-packages/altair/utils/mimebundle.py", line 60, in spec_to_mimebundle
    return altair_saver.render(spec, format, mode=mode, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/altair_saver/_core.py", line 255, in render
    Saver = _select_saver(method, mode=mode, fmt=fmt)
  File "/usr/local/lib/python3.9/site-packages/altair_saver/_core.py", line 67, in _select_saver
    if s.enabled() and fmt in s.valid_formats[mode]:
  File "/usr/local/lib/python3.9/site-packages/altair_saver/savers/_node.py", line 103, in enabled
    return bool(exec_path("vl2vg") and exec_path("vg2png"))
  File "/usr/local/lib/python3.9/site-packages/altair_saver/savers/_node.py", line 29, in exec_path
    for path in [None, npm_bin(global_=True), npm_bin(global_=False)]:
  File "/usr/local/lib/python3.9/site-packages/altair_saver/savers/_node.py", line 24, in npm_bin
    return check_output_with_stderr(cmd).decode().strip()
  File "/usr/local/lib/python3.9/site-packages/altair_saver/_utils.py", line 198, in check_output_with_stderr
    ps = subprocess.run(
  File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/npm', 'bin', '--global']' returned non-zero exit status 1.
Username anoduck
Exception Occurred Command '['/usr/bin/npm', 'bin', '--global']' returned non-zero exit status 1.

```

From the output, it is safe to say we got past the acceptance of variables part, and are at the point of successfully generating a graph. I will try it again at a later point in time.

**Comment by anoduck** [comment]
Found alternative

**Comment by nowiwr01w** [comment]
Same error
```
Run anmol098/waka-readme-stats@master
[25](https://github.com/nowiwr01w/nowiwr01w/actions/runs/3802442796/jobs/6467927617#step:3:26)
/usr/bin/docker run --name fe037c27d4631b045b7f355a416d4_4369f0 --label 290506 --workdir /github/workspace --rm -e "INPUT_WAKATIME_API_KEY" -e "INPUT_GH_TOKEN" -e "INPUT_PUSH_BRANCH_NAME" -e "INPUT_SHOW_OS" -e "INPUT_SHOW_PROJECTS" -e "INPUT_SHOW_EDITORS" -e "INPUT_SHOW_TIMEZONE" -e "INPUT_SHOW_COMMIT" -e "INPUT_SHOW_LANGUAGE" -e "INPUT_SHOW_LINES_OF_CODE" -e "INPUT_SHOW_LANGUAGE_PER_REPO" -e "INPUT_SHOW_LOC_CHART" -e "INPUT_SHOW_DAYS_OF_WEEK" -e "INPUT_SHOW_PROFILE_VIEWS" -e "INPUT_SHOW_SHORT_INFO" -e "INPUT_LOCALE" -e "INPUT_COMMIT_BY_ME" -e "INPUT_IGNORED_REPOS" -e "INPUT_COMMIT_MESSAGE" -e "INPUT_COMMIT_USERNAME" -e "INPUT_COMMIT_EMAIL" -e "INPUT_SHOW_UPDATED_DATE" -e "INPUT_UPDATED_DATE_FORMAT" -e "INPUT_SHOW_TOTAL_CODE_TIME" -e "INPUT_SYMBOL_VERSION" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/nowiwr01w/nowiwr01w":"/github/workspace" 290506:703fe037c27d4631b045b7f355a416d4
[26](https://github.com/nowiwr01w/nowiwr01w/actions/runs/3802442796/jobs/6467927617#step:3:27)
Traceback (most recent call last):
[27](https://github.com/nowiwr01w/nowiwr01w/actions/runs/3802442796/jobs/6467927617#step:3:28)
  File "/main.py", line 566, in <module>
[28](https://github.com/nowiwr01w/nowiwr01w/actions/runs/3802442796/jobs/6467927617#step:3:29)
    waka_stats = get_stats(g)
[29](https://github.com/nowiwr01w/nowiwr01w/actions/runs/3802442796/jobs/6467927617#step:3:30)
  File "/main.py", line 480, in get_stats
[30](https://github.com/nowiwr01w/nowiwr01w/actions/runs/3802442796/jobs/6467927617#step:3:31)
    yearly_data = get_yearly_data()
[31](https://github.com/nowiwr01w/nowiwr01w/actions/runs/3802442796/jobs/6467927617#step:3:32)
  File "/main.py", line 422, in get_yearly_data
[32](https://github.com/nowiwr01w/nowiwr01w/actions/runs/3802442796/jobs/6467927617#step:3:33)
    loc.plotLoc(yearly_data)
[33](https://github.com/nowiwr01w/nowiwr01w/actions/runs/3802442796/jobs/6467927617#step:3:34)
  File "/loc.py", line 38, in plotLoc
[34](https://github.com/nowiwr01w/nowiwr01w/actions/runs/3802442796/jobs/6467927617#step:3:35)
    graph.build_graph()
[35](https://github.com/nowiwr01w/nowiwr01w/actions/runs/3802442796/jobs/6467927617#step:3:36)
  File "/make_bar_graph.py", line 105, in build_graph
[36](https://github.com/nowiwr01w/nowiwr01w/actions/runs/3802442796/jobs/6467927617#step:3:37)
    chart.save('bar_graph.png')
[37](https://github.com/nowiwr01w/nowiwr01w/actions/runs/3802442796/jobs/6467927617#step:3:38)
  File "/usr/local/lib/python3.9/site-packages/altair/vegalite/v4/api.py", line 476, in save
[38](https://github.com/nowiwr01w/nowiwr01w/actions/runs/3802442796/jobs/6467927617#step:3:39)
    result = save(**kwds)
[39](https://github.com/nowiwr01w/nowiwr01w/actions/runs/3802442796/jobs/6467927617#step:3:40)
  File "/usr/local/lib/python3.9/site-packages/altair/utils/save.py", line 112, in save
[40](https://github.com/nowiwr01w/nowiwr01w/actions/runs/3802442796/jobs/6467927617#step:3:41)
    mimebundle = spec_to_mimebundle(
[41](https://github.com/nowiwr01w/nowiwr01w/actions/runs/3802442796/jobs/6467927617#step:3:42)
  File "/usr/local/lib/python3.9/site-packages/altair/utils/mimebundle.py", line 60, in spec_to_mimebundle
[42](https://github.com/nowiwr01w/nowiwr01w/actions/runs/3802442796/jobs/6467927617#step:3:43)
    return altair_saver.render(spec, format, mode=mode, **kwargs)
[43](https://github.com/nowiwr01w/nowiwr01w/actions/runs/3802442796/jobs/6467927617#step:3:44)
  File "/usr/local/lib/python3.9/site-packages/altair_saver/_core.py", line 255, in render
[44](https://github.com/nowiwr01w/nowiwr01w/actions/runs/3802442796/jobs/6467927617#step:3:45)
    Saver = _select_saver(method, mode=mode, fmt=fmt)
[45](https://github.com/nowiwr01w/nowiwr01w/actions/runs/3802442796/jobs/6467927617#step:3:46)
  File "/usr/local/lib/python3.9/site-packages/altair_saver/_core.py", line 67, in _select_saver
[46](https://github.com/nowiwr01w/nowiwr01w/actions/runs/3802442796/jobs/6467927617#step:3:47)
    if s.enabled() and fmt in s.valid_formats[mode]:
[47](https://github.com/nowiwr01w/nowiwr01w/actions/runs/3802442796/jobs/6467927617#step:3:48)
  File "/usr/local/lib/python3.9/site-packages/altair_saver/savers/_node.py", line 103, in enabled
[48](https://github.com/nowiwr01w/nowiwr01w/actions/runs/3802442796/jobs/6467927617#step:3:49)
    return bool(exec_path("vl2vg") and exec_path("vg2png"))
[49](https://github.com/nowiwr01w/nowiwr01w/actions/runs/3802442796/jobs/6467927617#step:3:50)
  File "/usr/local/lib/python3.9/site-packages/altair_saver/savers/_node.py", line 29, in exec_path
[50](https://github.com/nowiwr01w/nowiwr01w/actions/runs/3802442796/jobs/6467927617#step:3:51)
    for path in [None, npm_bin(global_=True), npm_bin(global_=False)]:
[51](https://github.com/nowiwr01w/nowiwr01w/actions/runs/3802442796/jobs/6467927617#step:3:52)
  File "/usr/local/lib/python3.9/site-packages/altair_saver/savers/_node.py", line 24, in npm_bin
[52](https://github.com/nowiwr01w/nowiwr01w/actions/runs/3802442796/jobs/6467927617#step:3:53)
    return check_output_with_stderr(cmd).decode().strip()
[53](https://github.com/nowiwr01w/nowiwr01w/actions/runs/3802442796/jobs/6467927617#step:3:54)
  File "/usr/local/lib/python3.9/site-packages/altair_saver/_utils.py", line 198, in check_output_with_stderr
[54](https://github.com/nowiwr01w/nowiwr01w/actions/runs/3802442796/jobs/6467927617#step:3:55)
    ps = subprocess.run(
[55](https://github.com/nowiwr01w/nowiwr01w/actions/runs/3802442796/jobs/6467927617#step:3:56)
  File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
[56](https://github.com/nowiwr01w/nowiwr01w/actions/runs/3802442796/jobs/6467927617#step:3:57)
    raise CalledProcessError(retcode, process.args,
[57](https://github.com/nowiwr01w/nowiwr01w/actions/runs/3802442796/jobs/6467927617#step:3:58)
subprocess.CalledProcessError: Command '['/usr/bin/npm', 'bin', '--global']' returned non-zero exit status 1.
[58](https://github.com/nowiwr01w/nowiwr01w/actions/runs/3802442796/jobs/6467927617#step:3:59)
Username nowiwr01w
```

Code:
```
name: Waka Readme

on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
```
