### ISSUE TITLE
when action are running, end everythin appears ok but when u go to the output return this:

### ISSUE THREAD

**Issue by Miguerfi** [anmol098/waka-readme-stats#350]
```
Traceback (most recent call last):
  File "/main.py", line 550, in <module>
    user_data = run_query(userInfoQuery)  # Execute the query
  File "/main.py", line 176, in run_query
    raise Exception("Query failed to run by returning code of {}. {}".format(request.status_code, query))
Exception: Query failed to run by returning code of 401. 
{
    viewer {
      login
      email
      id
    }
  }

Exception Occurred Query failed to run by returning code of 401. 
{
    viewer {
      login
      email
      id
    }
  }

```

**Comment by vgpastor** [comment]
This error it's because you dont have a right Github Token access
