### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Adlemex** [anmol098/waka-readme-stats#355]
**Describe the bug**
Not updated, because json.decoder.JSONDecodeError

**To Reproduce**
Run update

**Github repository link**
https://github.com/Adlemex/Adlemex

**Additional context**
```Traceback (most recent call last):
  File "/main.py", line 566, in <module>
    waka_stats = get_stats(g)
  File "/main.py", line 480, in get_stats
    yearly_data = get_yearly_data()
  File "/main.py", line 420, in get_yearly_data
    yearly_data = loc.calculateLoc()
  File "/loc.py", line [32](https://github.com/Adlemex/Adlemex/actions/runs/4031364587/jobs/6930665881#step:3:33), in calculateLoc
    self.getCommitStat(repo['node'], yearly_data)
  File "/loc.py", line 65, in getCommitStat
    filteredCommitsResult = self.run_query_v3(filteredCommitsEndPoint)
  File "/loc.py", line 49, in run_query_v3
    return request.json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line [33](https://github.com/Adlemex/Adlemex/actions/runs/4031364587/jobs/6930665881#step:3:34)7, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line [35](https://github.com/Adlemex/Adlemex/actions/runs/4031364587/jobs/6930665881#step:3:36)5, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Username Adlemex
Exception Occurred Expecting value: line 1 column 1 (char 0)```

**Comment by vitaliy-art** [comment]
Yeah, it works properly now. The error was raised while first manually workflow run. Automatic run completed successfully.
