### ISSUE TITLE
BUG - IndexError: list index out of range

### ISSUE THREAD

**Issue by infinitel8p** [anmol098/waka-readme-stats#356]
**Describe the bug**
When running the workflow i get:
```
Traceback (most recent call last):
  File "/main.py", line 566, in <module>
    waka_stats = get_stats(g)
  File "/main.py", line 506, in get_stats
    stats += get_short_info(github)
  File "/main.py", line 447, in get_short_info
    total = data['years'][0]['total']
IndexError: list index out of range
Username infinitel8p
Exception Occurred list index out of range
```

**To Reproduce**
Run workflow manually.
I previously used https://github.com/athul/athul for my stats, now i added GH_Token to my secrets and changed the yml to fit this repos requirements. I get this error when running the workflow

![image](https://user-images.githubusercontent.com/50703696/215407930-94c7ba2c-0a70-4947-b36d-958ab24a1b42.png)

**Github repository link**
https://github.com/infinitel8p/infinitel8p/blob/main/.github/workflows/waka-readme.yml

**Comment by infinitel8p** [comment]
Ok i really works when having a public profile. Everything is a bit crooked but no error anymore
![image](https://user-images.githubusercontent.com/50703696/216295672-749390d5-be0d-416d-8dee-2272a47e1abd.png)

Next step would be having it working on a private profile like athuls stats, looking foreward to that

**Comment by infinitel8p** [comment]
is there really no way to create at least a minimal statwindow like https://github.com/athul/athul does? 
Like if you have a private profile use his workflow to fetch at least some data or something like that.

Apart from that i have some questions now that it works for me:
- how can i make them not crooked
![image](https://user-images.githubusercontent.com/50703696/216297856-db5f88fc-0237-4372-84b9-469b343c1751.png)
- Is there a way to show more/all languages used
![image](https://user-images.githubusercontent.com/50703696/216298168-b26f1418-f920-4440-b44d-176c85a3abfa.png)
