### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by jampow** [anmol098/waka-readme-stats#361]
**Describe the bug**
Cadence is silently failing

**To Reproduce**
1. clone the project and access the repo folder
2. build the container with `docker build -t waka-readme-stats:latest -f Dockerfile .`
3. run the container with (please, replace `<wakatime_token>` and `<github_token>` with something valid:

```
docker run --workdir /github/workspace --rm -e INPUT_WAKATIME_API_KEY=<wakatime_token> -e INPUT_GH_TOKEN=<github_token> -e INPUT_SHOW_PROJECTS=False -e INPUT_SHOW_LINES_OF_CODE=True -e INPUT_LOCALE=pt-BR -e INPUT_SECTION_NAME=waka -e INPUT_PUSH_BRANCH_NAME=master -e INPUT_SHOW_OS=True -e INPUT_SHOW_EDITORS=True -e INPUT_SHOW_TIMEZONE=True -e INPUT_SHOW_COMMIT=True -e INPUT_SHOW_LANGUAGE=True -e INPUT_SHOW_LANGUAGE_PER_REPO=True -e INPUT_SHOW_LOC_CHART=True -e INPUT_SHOW_DAYS_OF_WEEK=True -e INPUT_SHOW_PROFILE_VIEWS=True -e INPUT_SHOW_SHORT_INFO=True -e INPUT_COMMIT_BY_ME=False -e INPUT_COMMIT_MESSAGE='Updated as test' -e INPUT_COMMIT_USERNAME=Gian -e INPUT_COMMIT_EMAIL=test@test.com -e INPUT_SHOW_UPDATED_DATE=True -e INPUT_UPDATED_DATE_FORMAT='%d/%m/%Y %H:%M:%S' -e INPUT_SHOW_TOTAL_CODE_TIME=True -e INPUT_SYMBOL_VERSION=1 -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v github_home:/github/home -v github_workflow:/github/workflow -v runner_file_commands:/github/file_commands -v jampow:/github/workspace waka-readme-stats:latest
```

```
Traceback (most recent call last):
  File "/main.py", line 568, in <module>
    waka_stats = get_stats(g)
  File "/main.py", line 482, in get_stats
    yearly_data = get_yearly_data()
  File "/main.py", line 424, in get_yearly_data
    loc.plotLoc(yearly_data)
  File "/loc.py", line 38, in plotLoc
    graph.build_graph()
  File "/make_bar_graph.py", line 43, in build_graph
    if colors[language]['color'] is not None:
KeyError: 'Cadence'
Username jampow
Exception Occurred 'Cadence'
```

**Expected behavior**
Build without failure or give an exit code different of 0, to mark it as failed

**Github repository link**
[repository](https://github.com/jampow/jampow)
[failed build](https://github.com/jampow/jampow/actions/runs/4127310416/jobs/7130363118)

**Comment by pseusys** [comment]
This is happening because this repo contains it's own list of langauges with colors, which is not always up-to-date with GitHub. Please, take a look at [this pull request](https://github.com/anmol098/waka-readme-stats/pull/341) - it's intended to solve the problem.
