### ISSUE TITLE
If a repo is empty, a null pointer exception will occur

### ISSUE THREAD

**Issue by VeejaLiu** [anmol098/waka-readme-stats#370]
<img width="2357" alt="image" src="https://user-images.githubusercontent.com/22064617/219532713-4d52eadc-bf42-496d-9dd5-afa028e2e2c9.png">

**Comment by mfsbo** [comment]
Same happened with me
```
Traceback (most recent call last):
  File "/waka-readme-stats/main.py", line 454, in <module>
    run(main())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/waka-readme-stats/main.py", line [42](https://github.com/mfsbo/mfsbo/actions/runs/4199319812/jobs/7292602991#step:3:43)6, in main
    waka_stats = await get_stats(g)
  File "/waka-readme-stats/main.py", line 356, in get_stats
    await get_yearly_data()
  File "/waka-readme-stats/main.py", line 297, in get_yearly_data
    yearly_data = await loc.calculateLoc()
  File "/waka-readme-stats/loc.py", line 26, in calculateLoc
    await self.getCommitStat(repo['node'], yearly_data)
  File "/waka-readme-stats/loc.py", line [46](https://github.com/mfsbo/mfsbo/actions/runs/4199319812/jobs/7292602991#step:3:47), in getCommitStat
    commit_data = await DownloadManager.get_remote_graphql("repository_commit_list", owner=repoDetails["owner"]["login"], name=repoDetails['name'], id=self.user.node_id)
  File "/waka-readme-stats/download_manager.py", line 202, in get_remote_graphql
    raise Exception(f"Query '{query}' failed to run by returning code of {res.status_code}: {res.json()}")
Exception: Query 'repository_commit_list' failed to run by returning code of [50](https://github.com/mfsbo/mfsbo/actions/runs/4199319812/jobs/7292602991#step:3:51)2: {'data': None, 'errors': [{'message': 'Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `1BC1:0306:[54](https://github.com/mfsbo/mfsbo/actions/runs/4199319812/jobs/7292602991#step:3:55)642BA:AC90D8A:63EF6602` when reporting this issue.'}]}
sys:1: RuntimeWarning: coroutine 'AsyncClient.get' was never awaited
```
This is what I got if it helps

**Comment by VeejaLiu** [comment]
Coll!!!

**Comment by mfsbo** [comment]
I have checked mine and rerun the action on github and it failed. However as suggested I will wait for #375 to complete as repo is no longer empty and related to this issue. Its not big as well as I have no commits on it at all. I was just creator of the repo. As it was new it appears at bottom of list at 99/100 so looks like its an issue but the issue might be pagination on one of the other big repos due to pagination.
