### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by ssoad** [anmol098/waka-readme-stats#376]
Traceback (most recent call last):
  File "/waka-readme-stats/main.py", line 457, in <module>
    run(main())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/waka-readme-stats/main.py", line 429, in main
    waka_stats = await get_stats(g)
  File "/waka-readme-stats/main.py", line 359, in get_stats
    await get_yearly_data()
  File "/waka-readme-stats/main.py", line 300, in get_yearly_data
    yearly_data = await loc.calculateLoc()
  File "/waka-readme-stats/loc.py", line 26, in calculateLoc
    await self.getCommitStat(repo['node'], yearly_data)
  File "/waka-readme-stats/loc.py", line 46, in getCommitStat
    commit_data = await DownloadManager.get_remote_graphql("repository_commit_list", owner=repoDetails["owner"]["login"], name=repoDetails['name'], id=self.user.node_id)
  File "/waka-readme-stats/download_manager.py", line 202, in get_remote_graphql
    raise Exception(f"Query '{query}' failed to run by returning code of {res.status_code}: {res.json()}")
Exception: Query 'repository_commit_list' failed to run by returning code of 502: {'data': None, 'errors': [{'message': 'Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `3441:6F8C:2[86](https://github.com/ssoad/ssoad/actions/runs/4215057981/jobs/7315930230#step:3:87)B211:53AA76C:63F1CA4F` when reporting this issue.'}]}
sys:1: RuntimeWarning: coroutine 'AsyncClient.get' was never awaited

**Comment by ssoad** [comment]
Still Same Issue

**Comment by ssoad** [comment]
@pseusys

**Comment by ssoad** [comment]
@pseusys  finally I got the problem. One of my repository has commits from Non-GitHub Email basically the user change his email. After Remove these commits the problem was solved. Thanks for your time

**Comment by KingNNT** [comment]
![image](https://user-images.githubusercontent.com/38956244/224090523-ab84fd15-1e86-4d3a-804c-47cc96831913.png)

Hi, I'm getting this error quite a few times now, it's been around for at least the last 1-2 weeks or so.
I have read through a few related issues but still can't fix this problem, can you help me

This is my repo: https://github.com/KingNNT/KingNNT
