### ISSUE TITLE
FileNotFoundError: 'sources/translation.json'

### ISSUE THREAD

**Issue by kitagawa-hr** [anmol098/waka-readme-stats#398]
**Describe the bug**

FileNotFoundError caused when running a job

Below is a error log

```
Traceback (most recent call last):
  File "/waka-readme-stats/main.py", line 200, in <module>
    run(main())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/waka-readme-stats/main.py", line 183, in main
    init_localization_manager()
  File "/waka-readme-stats/manager_file.py", line 13, in init_localization_manager
    FileManager.load_localization("translation.json")
  File "/waka-readme-stats/manager_file.py", line [31](https://github.com/kitagawa-hr/kitagawa-hr/actions/runs/4288302604/jobs/7470157010#step:3:32), in load_localization
    with open(join("sources", file), encoding="utf-8") as config_file:
FileNotFoundError: [Errno 2] No such file or directory: 'sources/translation.json'
sys:[1](https://github.com/kitagawa-hr/kitagawa-hr/actions/runs/4288302604/jobs/7470157010#step:4:1): RuntimeWarning: coroutine 'AsyncClient.get' was never awaited
```

Probably because `sources` directory doesn't exist in a container.

https://github.com/anmol098/waka-readme-stats/blob/356e4437f1a0a2b0c70d0ca1dc7a5d4123fbbabb/Dockerfile#L11

**Github repository link**

https://github.com/kitagawa-hr/kitagawa-hr/actions/runs/4288302604/jobs/7470157010

**Comment by sun0225SUN** [comment]
me too

**Comment by VeejaLiu** [comment]
same error
I didn't do anything. Errors began to appear today.
<img width="2154" alt="image" src="https://user-images.githubusercontent.com/22064617/221740695-90b8d93c-08ba-4918-8dc0-0bd46d63a316.png">

**Comment by Fanduzi** [comment]
same error

**Comment by yxlazy** [comment]
same error

**Comment by gentildpinto** [comment]
I've the same issue

```sh
Traceback (most recent call last):
  File "/waka-readme-stats/main.py", line 200, in <module>
    run(main())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/waka-readme-stats/main.py", line 183, in main
    init_localization_manager()
  File "/waka-readme-stats/manager_file.py", line 13, in init_localization_manager
    FileManager.load_localization("translation.json")
  File "/waka-readme-stats/manager_file.py", line 31, in load_localization
    with open(join("sources", file), encoding="utf-8") as config_file:
FileNotFoundError: [Errno 2] No such file or directory: 'sources/translation.json'
sys:1: RuntimeWarning: coroutine 'AsyncClient.get' was never awaited
```

**Comment by Davenchy** [comment]
the same error
```
Traceback (most recent call last):
  File "/waka-readme-stats/main.py", line 200, in <module>
    run(main())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/waka-readme-stats/main.py", line 183, in main
    init_localization_manager()
  File "/waka-readme-stats/manager_file.py", line 13, in init_localization_manager
    FileManager.load_localization("translation.json")
  File "/waka-readme-stats/manager_file.py", line [31](https://github.com/Davenchy/Davenchy/actions/runs/4288624318/jobs/7479735479#step:3:32), in load_localization
    with open(join("sources", file), encoding="utf-8") as config_file:
FileNotFoundError: [Errno 2] No such file or directory: 'sources/translation.json'
sys:1: RuntimeWarning: coroutine 'AsyncClient.get' was never awaited
```

**Comment by Snailedlt** [comment]
Same error here:
```shell
Traceback (most recent call last):
  File "/waka-readme-stats/main.py", line 200, in <module>
    run(main())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line [64](https://github.com/Snailedlt/Snailedlt/actions/runs/4292924236/jobs/7480732250#step:3:65)7, in run_until_complete
    return future.result()
  File "/waka-readme-stats/main.py", line 183, in main
    init_localization_manager()
  File "/waka-readme-stats/manager_file.py", line 13, in init_localization_manager
    FileManager.load_localization("translation.json")
  File "/waka-readme-stats/manager_file.py", line 31, in load_localization
    with open(join("sources", file), encoding="utf-8") as config_file:
FileNotFoundError: [Errno 2] No such file or directory: 'sources/translation.json'
sys:1: RuntimeWarning: coroutine 'AsyncClient.get' was never awaited
##[debug]Docker Action run completed with exit code 1
##[debug]Finishing: Run anmol098/waka-readme-stats@master
```

**Comment by MAbbara** [comment]
Same error here:
`Traceback (most recent call last):
  File "/waka-readme-stats/main.py", line 200, in <module>
    run(main())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/waka-readme-stats/main.py", line 183, in main
    init_localization_manager()
  File "/waka-readme-stats/manager_file.py", line 13, in init_localization_manager
    FileManager.load_localization("translation.json")
  File "/waka-readme-stats/manager_file.py", line [31](https://github.com/MAbbara/MAbbara/actions/runs/4296266635/jobs/7487812553#step:3:32), in load_localization
    with open(join("sources", file), encoding="utf-8") as config_file:
FileNotFoundError: [Errno 2] No such file or directory: 'sources/translation.json'
sys:1: RuntimeWarning: coroutine 'AsyncClient.get' was never awaited`
