### ISSUE TITLE
github.GithubException.UnknownObjectException: 404

### ISSUE THREAD

**Issue by aravindvnair99** [anmol098/waka-readme-stats#403]
Merging of #401 led to a new error

```
Traceback (most recent call last):
  File "/waka-readme-stats/manager_github.py", line 144, in update_chart
    contents = GitHubManager.REPO.get_contents(chart_path)
  File "/usr/local/lib/python3.9/site-packages/github/Repository.py", line 1868, in get_contents
    headers, data = self._requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.9/site-packages/github/Requester.py", line 400, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.9/site-packages/github/Requester.py", line 425, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/repos#get-repository-content"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/waka-readme-stats/main.py", line 200, in <module>
    run(main())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/waka-readme-stats/main.py", line 186, in main
    stats = await get_stats()
  File "/waka-readme-stats/main.py", line 166, in get_stats
    stats += GHM.update_chart(GRAPH_PATH)
  File "/waka-readme-stats/manager_github.py", line 148, in update_chart
    GitHubManager.REPO.create_file(chart_path, "Charts Added", data, committer=GitHubManager._get_author())
  File "/usr/local/lib/python3.9/site-packages/github/Repository.py", line 2178, in create_file
    headers, data = self._requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.9/site-packages/github/Requester.py", line [40](https://github.com/aravindvnair99/AravindVNair99/actions/runs/4296891643/jobs/7489182654#step:3:41)0, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.9/site-packages/github/Requester.py", line [42](https://github.com/aravindvnair99/AravindVNair99/actions/runs/4296891643/jobs/7489182654#step:3:43)5, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 422 {"message": "path contains a malformed path component", "errors": [{"resource": "Commit", "field": "path", "code": "invalid"}], "documentation_url": "https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}
```

**Comment by aravindvnair99** [comment]
Execution history: https://github.com/aravindvnair99/AravindVNair99/actions/runs/4296891643/jobs/7489182654#step:3:27

**Comment by VeejaLiu** [comment]
same error:
```
Traceback (most recent call last):
  File "/waka-readme-stats/manager_github.py", line 144, in update_chart
    contents = GitHubManager.REPO.get_contents(chart_path)
  File "/usr/local/lib/python3.9/site-packages/github/Repository.py", line 1868, in get_contents
    headers, data = self._requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.9/site-packages/github/Requester.py", line 400, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.9/site-packages/github/Requester.py", line 425, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/repos#get-repository-content"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/waka-readme-stats/main.py", line 200, in <module>
    run(main())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/waka-readme-stats/main.py", line 186, in main
    stats = await get_stats()
  File "/waka-readme-stats/main.py", line 166, in get_stats
    stats += GHM.update_chart(GRAPH_PATH)
  File "/waka-readme-stats/manager_github.py", line 148, in update_chart
    GitHubManager.REPO.create_file(chart_path, "Charts Added", data, committer=GitHubManager._get_author())
  File "/usr/local/lib/python3.9/site-packages/github/Repository.py", line 2178, in create_file
    headers, data = self._requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.9/site-packages/github/Requester.py", line [40](https://github.com/VeejaLiu/VeejaLiu/actions/runs/4299157200/jobs/7494077108#step:3:41)0, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.9/site-packages/github/Requester.py", line [42](https://github.com/VeejaLiu/VeejaLiu/actions/runs/4299157200/jobs/7494077108#step:3:43)5, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 422 {"message": "path contains a malformed path component", "errors": [{"resource": "Commit", "field": "path", "code": "invalid"}], "documentation_url": "https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}
```
