### ISSUE TITLE
coroutine 'AsyncClient.get' was never awaited

### ISSUE THREAD

**Issue by VeejaLiu** [anmol098/waka-readme-stats#412]
```
Traceback (most recent call last):
  File "/waka-readme-stats/main.py", line 200, in <module>
    run(main())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/waka-readme-stats/main.py", line 186, in main
    stats = await get_stats()
  File "/waka-readme-stats/main.py", line 141, in get_stats
    data = await DM.get_remote_json("waka_all")
  File "/waka-readme-stats/manager_download.py", line 218, in get_remote_json
    return await DownloadManager._get_remote_resource(resource, None)
  File "/waka-readme-stats/manager_download.py", line 209, in _get_remote_resource
    raise Exception(f"Query '{res.url}' failed to run by returning code of {res.status_code}: {res.json()}")
  File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 755, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line [33](https://github.com/VeejaLiu/VeejaLiu/actions/runs/4361348781/jobs/7625163710#step:3:34)7, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line [35](https://github.com/VeejaLiu/VeejaLiu/actions/runs/4361348781/jobs/7625163710#step:3:36)5, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
sys:1: RuntimeWarning: coroutine 'AsyncClient.get' was never awaited
```

**Comment by yxlazy** [comment]
same error
```text
Traceback (most recent call last):
  File "/waka-readme-stats/main.py", line 200, in <module>
    run(main())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/waka-readme-stats/main.py", line 186, in main
    stats = await get_stats()
  File "/waka-readme-stats/main.py", line 141, in get_stats
    data = await DM.get_remote_json("waka_all")
  File "/waka-readme-stats/manager_download.py", line 218, in get_remote_json
    return await DownloadManager._get_remote_resource(resource, None)
  File "/waka-readme-stats/manager_download.py", line 209, in _get_remote_resource
    raise Exception(f"Query '{res.url}' failed to run by returning code of {res.status_code}: {res.json()}")
  File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 755, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line [33](https://github.com/yxlazy/yxlazy/actions/runs/4361926876/jobs/7626278693#step:3:34)7, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line [35](https://github.com/yxlazy/yxlazy/actions/runs/4361926876/jobs/7626278693#step:3:36)5, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
sys:1: RuntimeWarning: coroutine 'AsyncClient.get' was never awaited
```

**Comment by VeejaLiu** [comment]
Good now. If happen again, I will reply under it.

**Comment by VeejaLiu** [comment]
@pseusys Thank you for your detailed explanation. Best wishes to you!
