### ISSUE TITLE
BUG: ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by StarHeartHunt** [anmol098/waka-readme-stats#427]
**Describe the bug**
It seems that some calculations in action didn't consider some edge cases.

**Expected behavior**
No error should occur.

**Github repository link**
https://github.com/StarHeartHunt/StarHeartHunt/actions/runs/4408405650/jobs/7723368320

```python
Traceback (most recent call last):
  File "/waka-readme-stats/main.py", line 221, in <module>
    run(main())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/waka-readme-stats/main.py", line 208, in main
    stats = await get_stats()
            ^^^^^^^^^^^^^^^^^
  File "/waka-readme-stats/main.py", line 180, in get_stats
    stats += await get_waka_time_stats(repositories, commit_data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/waka-readme-stats/main.py", line [36](https://github.com/StarHeartHunt/StarHeartHunt/actions/runs/4408405650/jobs/7723368320#step:3:37), in get_waka_time_stats
    stats += f"{await make_commit_day_time_list(data['data']['timezone'], repositories, commit_dates)}\n\n"
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/waka-readme-stats/graphics_list_formatter.py", line 108, in make_commit_day_time_list
    dt_percents = [round((day_time / sum_day) * 100, 2) for day_time in day_times]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/waka-readme-stats/graphics_list_formatter.py", line 108, in <listcomp>
    dt_percents = [round((day_time / sum_day) * 100, 2) for day_time in day_times]
                          ~~~~~~~~~^~~~~~~~~
ZeroDivisionError: division by zero
sys:1: RuntimeWarning: coroutine 'AsyncClient.get' was never awaited
```

**Comment by wufeng15226** [comment]
same issue

**Comment by dhvcc** [comment]
Same here, hope this is resolved soon 🤞

**Comment by NONPLAYT** [comment]
same

**Comment by IrisesD** [comment]
same issue

**Comment by fabian4** [comment]
same issue
