### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by MengFanjun020906** [anmol098/waka-readme-stats#496]
**Describe the bug**
When runworkflow，AssertionError

**To Reproduce**
1. Go to Actions
2. Click on 'run workflow‘
3. See error

**Expected behavior**
I want to make waka-readme success

**Additional context**
The error：
Traceback (most recent call last):
  File "/waka-readme-stats/main.py", line 2[30](https://github.com/MengFanjun020906/MengFanjun020906/actions/runs/7430137762/job/20219498327#step:3:31), in <module>
    run(main())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/waka-readme-stats/main.py", line 212, in main
    init_github_manager()
  File "/waka-readme-stats/manager_github.py", line 22, in init_github_manager
    GitHubManager.prepare_github_env()
  File "/waka-readme-stats/manager_github.py", line [47](https://github.com/MengFanjun020906/MengFanjun020906/actions/runs/7430137762/job/20219498327#step:3:48), in prepare_github_env
    github = Github(EM.GH_TOKEN)
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/github/MainClass.py", line 150, in __init__
    auth = Auth.Token(login_or_token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/github/Auth.py", line 108, in __init__
    assert len(token) > 0
           ^^^^^

**Comment by MengFanjun020906** [comment]
you can see this picture 
![image](https://github.com/anmol098/waka-readme-stats/assets/42081913/4a0a90ee-081f-43a3-aa4e-07c234ccd560)

**Comment by v1peridae** [comment]
I'm experiencing the same issue. I have been experiencing it since December 3rd.

**Comment by v1peridae** [comment]
Fixed for me!

**Comment by v1peridae** [comment]
I reset the secrets and it worked

**Comment by Prathamesh-B** [comment]
Yeah, I experienced the same issue, and resetting the token resolved it. However, I believe there should be some exception handling in place.

**Comment by dyzdyz010** [comment]
How to reset the token? I've regenerated my token and set repo's secret multiple times, yet the error remains.

**Comment by dyzdyz010** [comment]
Solved, just add environment to .yml file, because secrets are defined in envionments.

**Comment by MengFanjun020906** [comment]
I have solved, you need insure the token in .yml file.
