### ISSUE TITLE
BUG| Flag SHOW_LOC_CHART: "True" Failed

### ISSUE THREAD

**Issue by liumy-lay** [anmol098/waka-readme-stats#512]
**Describe the bug**
If the Flag `SHOW_LOC_CHART` is not filled in in YML, the default is `"True"` . 

At the beginning of Github Action Faild, I couldn't find something wrong, 

but when I added `show_loc_chart: "Flase"`, GitHub Action was successful.

Here is the detailed bug description：
```
/usr/bin/docker run --name wakareadmestatswakareadmestatsmaster_0[2](https://github.com/liumy-lay/liumy-lay/actions/runs/10001455264/job/27645080631#step:3:2)bc0b --label b[3](https://github.com/liumy-lay/liumy-lay/actions/runs/10001455264/job/27645080631#step:3:3)1cf3 --workdir /github/workspace --rm -e "INPUT_WAKATIME_API_KEY" -e "INPUT_GH_TOKEN" -e "INPUT_LOCALE" -e "INPUT_SHOW_OS" -e "INPUT_SHOW_PROJECTS" -e "INPUT_SHOW_TOTAL_CODE_TIME" -e "INPUT_SHOW_LINES_OF_CODE" -e "INPUT_SHOW_PROFILE_VIEWS" -e "INPUT_SHOW_COMMIT" -e "INPUT_SHOW_TIMEZONE" -e "INPUT_SHOW_SHORT_INFO" -e "INPUT_SYMBOL_VERSION" -e "INPUT_SHOW_LOC_CHART" -e "INPUT_SECTION_NAME" -e "INPUT_PULL_BRANCH_NAME" -e "INPUT_PUSH_BRANCH_NAME" -e "INPUT_SHOW_EDITORS" -e "INPUT_SHOW_LANGUAGE" -e "INPUT_SHOW_LANGUAGE_PER_REPO" -e "INPUT_SHOW_DAYS_OF_WEEK" -e "INPUT_SHOW_UPDATED_DATE" -e "INPUT_COMMIT_BY_ME" -e "INPUT_COMMIT_MESSAGE" -e "INPUT_COMMIT_USERNAME" -e "INPUT_COMMIT_EMAIL" -e "INPUT_COMMIT_SINGLE" -e "INPUT_UPDATED_DATE_FORMAT" -e "INPUT_IGNORED_REPOS" -e "INPUT_DEBUG_LOGGING" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/liumy-lay/liumy-lay":"/github/workspace" wakareadmestats/waka-readme-stats:master
Traceback (most recent call last):
  File "/waka-readme-stats/main.py", line 230, in <module>
    run(main())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 6[5](https://github.com/liumy-lay/liumy-lay/actions/runs/10001455264/job/27645080631#step:3:5)3, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/waka-readme-stats/main.py", line 217, in main
    stats = await get_stats()
            ^^^^^^^^^^^^^^^^^
  File "/waka-readme-stats/main.py", line 19[6](https://github.com/liumy-lay/liumy-lay/actions/runs/10001455264/job/27645080631#step:3:6), in get_stats
    await create_loc_graph(yearly_data, GRAPH_PATH)
  File "/waka-readme-stats/graphics_chart_drawer.py", line 69, in create_loc_graph
    max_offset = 0.05 * amax(cumulative.flatten())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 282[7](https://github.com/liumy-lay/liumy-lay/actions/runs/10001455264/job/27645080631#step:3:7), in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line [8](https://github.com/liumy-lay/liumy-lay/actions/runs/10001455264/job/27645080631#step:3:8)8, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: zero-size array to reduction operation maximum which has no identity
sys:1: RuntimeWarning: coroutine 'AsyncClient.get' was never awaited
```
**Expected behavior**

For new users of Wakatime，to avoid `ACTION FAILED`  the flag `SHOW_LOC_CHART` should set to `False`  by default in the original code.

![image](https://github.com/user-attachments/assets/82d9686a-5e06-4a47-a31b-6eba0437c041)

**Comment by dappsar** [comment]
Same error with SHOW_LOC_CHART = False.
This is the configuration I am using:

```name: waka Readme # https://github.com/marketplace/actions/profile-readme-development-stats

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:00AM UTC
    - cron: '30 18 * * *'

jobs:
  update-readme: # https://wakatime.com/projects
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master #PLEASE USE MASTER BRANCH
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # https://wakatime.com/api-key
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_LINES_OF_CODE: "True" 
          SHOW_LOC_CHART: "False"
          LOCALE: "en"

```
