### ISSUE TITLE
BUG max() arg is an empty sequence

### ISSUE THREAD

**Issue by dappsar** [anmol098/waka-readme-stats#522]
**Describe the bug**
From one day to the next, it stopped working with the following error:

```Traceback (most recent call last):
  File "/waka-readme-stats/main.py", line 230, in <module>
    run(main())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/waka-readme-stats/main.py", line 217, in main
    stats = await get_stats()
            ^^^^^^^^^^^^^^^^^
  File "/waka-readme-stats/main.py", line 193, in get_stats
    stats += f"{make_language_per_repo_list(repositories)}\n\n"
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/waka-readme-stats/graphics_list_formatter.py", line 141, in make_language_per_repo_list
    top_language = max(list(language_count.keys()), key=lambda x: language_count[x]["count"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: max() arg is an empty sequence
sys:1: RuntimeWarning: coroutine 'AsyncClient.get' was never awaited```


There were no changes to the readme or GitHub action until I detected the error, at which point I started testing different options, but with no positive results.


**Github repository link**
https://github.com/dappsar/dappsar

**Additional context**
It was working until last week.

**Comment by beatrizsmerino** [comment]
![Captura de pantalla 2024-08-19 a las 15 33 25](https://github.com/user-attachments/assets/2619d247-a02e-4c83-9faa-1db1798dd743)
I think I have the same [issue](https://github.com/beatrizsmerino/beatrizsmerino/actions/runs/10453924160/job/28945383171)

**Comment by 0xM4LL0C** [comment]
I have the same issue
