### ISSUE TITLE
BUG: Exception occurred 'Europe/Kyiv'

### ISSUE THREAD

**Issue by Searge** [anmol098/waka-readme-stats#533]
**Describe the bug**
Hello,

I got next error message from the latest (v4) tag:

```
Traceback (most recent call last):
Username Searge
Exception occurred 'Europe/Kyiv'
Exception occurred 'Europe/Kyiv'
Exception occurred 'Europe/Kyiv'
Exception occurred 'Europe/Kyiv'
Exception occurred 'Europe/Kyiv'
Exception occurred 'Europe/Kyiv'
Exception occurred 'Europe/Kyiv'
Exception occurred 'Europe/Kyiv'
Exception occurred 'Europe/Kyiv'
Exception occurred 'Europe/Kyiv'
Exception occurred 'Europe/Kyiv'
Exception occurred 'Europe/Kyiv'
Exception occurred 'Europe/Kyiv'
Exception occurred 'Europe/Kyiv'
Exception occurred 'Europe/Kyiv'
Exception occurred 'Europe/Kyiv'
Exception occurred 'Europe/Kyiv'
Exception occurred 'Europe/Kyiv'
Exception occurred 'Europe/Kyiv'
Exception occurred 'Europe/Kyiv'
Exception Occurred division by zero
  File "/main.py", line 511, in <module>
    waka_stats = get_stats(g)
  File "/main.py", line 456, in get_stats
    stats += get_waka_time_stats()
  File "/main.py", line 307, in get_waka_time_stats
    stats = stats + generate_commit_list(tz=data['data']['timezone']) + '\n\n'
  File "/main.py", line 256, in generate_commit_list
    "percent": round((morning / sumAll) * 100, 2)},
ZeroDivisionError: division by zero
```
The job with error: [Run anmol098/waka-readme-stats@v4](https://github.com/Searge/Searge/actions/runs/11701512866/job/32587769275#step:3:21)

**Expected behavior**
I am expecting the job will successes ;-)

**Github repository link**
The link to the [github.com/Searge/Searge/.github/workflows/wakatime.yml](https://github.com/Searge/Searge/blob/main/.github/workflows/wakatime.yml#L14-L22)

**Comment by Searge** [comment]
Hello,

Just want to let you know, that [issue](https://github.com/Searge/Searge/actions/runs/11963864690/job/33355128037) still persists.
