### ISSUE TITLE
Getting some sort of ApacheConf exception

### ISSUE THREAD

**Issue by grigala** [anmol098/waka-readme-stats#54]
**Describe the bug**
The action fails due to the ApacheConf exception

<details>
<summary> Run anmol098/waka-readme-stats@master </summary>

```
SHOW_TIMEZONE: True
    SHOW_COMMIT: True
    SHOW_LANGUAGE: True
    SHOW_LINES_OF_CODE: False
    SHOW_LANGUAGE_PER_REPO: True
    SHOW_LOC_CHART: True
    SHOW_DAYS_OF_WEEK: True
    SHOW_PROFILE_VIEWS: True
    SHOW_SHORT_INFO: True
/usr/bin/docker run --name cb3bf5acb3173a45008aea8fd68e3c2502_373029 --label 8118cb --workdir /github/workspace --rm -e INPUT_WAKATIME_API_KEY -e INPUT_GH_TOKEN -e INPUT_SHOW_OS -e INPUT_SHOW_PROJECTS -e INPUT_SHOW_EDITORS -e INPUT_SHOW_TIMEZONE -e INPUT_SHOW_COMMIT -e INPUT_SHOW_LANGUAGE -e INPUT_SHOW_LINES_OF_CODE -e INPUT_SHOW_LANGUAGE_PER_REPO -e INPUT_SHOW_LOC_CHART -e INPUT_SHOW_DAYS_OF_WEEK -e INPUT_SHOW_PROFILE_VIEWS -e INPUT_SHOW_SHORT_INFO -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/grigala/grigala":"/github/workspace" 8118cb:3bf5acb3173a45008aea8fd68e3c2502
```

</details>

```
Please Ignore this exception 'NoneType' object is not subscriptable
Exception Occurred 'ApacheConf'
Traceback (most recent call last):
  File "/main.py", line 478, in <module>
    waka_stats = get_stats(g)
  File "/main.py", line 447, in get_stats
    loc.calculateLoc()
  File "/loc.py", line 33, in calculateLoc
    graph_file = graph.build_graph()
  File "/make_bar_graph.py", line 43, in build_graph
    if colors[language]['color'] is not None:
```

**Expected behavior**
Should be running without problems, the config seems to be correct - another [version of Waka statistics](https://github.com/athul/waka-readme) works fine. 

**Github repository link**
[waka-readme-detailed.yml](https://github.com/grigala/grigala/blob/master/.github/workflows/waka-readme-detailed.yml)

**Additional context**
<details>
<summary>Screenshot</summary>
![screenshot](https://user-images.githubusercontent.com/2084794/89879118-bf6dbd80-dbc2-11ea-9ae8-946f4cfe33cc.png)
</details>

**Comment by grigala** [comment]
Disabled `SHOW_LOC_CHART` and it works. Something must be happening during bar graph generation.
