### ISSUE TITLE
[BUG] 404 Error on Start

### ISSUE THREAD

**Issue by itsnebulalol** [anmol098/waka-readme-stats#90]
**Describe the bug**
The workflow spits out a 404 error on start.

**To Reproduce**
1. Add the example YML to .github/workflows
2. Add a secret called WAKATIME_API_KEY to the repo.
3. Run the workflow.
4. Get the error.

**Expected behavior**
I expect the workflow to edit the readme, meanwhile it does nothing and spits out a 404 error. The workflow from athul/waka-readme works fine.

**Github repository link**
https://github.com/itsnebulalol/itsnebulalol

**Additional context**
I have linked the repository where the workflow was being used, and the workflow is named waka-readme.yml

**Workflow YML**
```yaml
name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 8AM EDT (12:00 UTC)
    - cron: '0 12 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
```

**Error**
```
Traceback (most recent call last):
github-actions[bot]
  File "/main.py", line 495, in <module>
Exception Occurred 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/repos#get-a-repository"}
    repo = g.get_repo(f"{username}/{username}")
  File "/usr/local/lib/python3.8/site-packages/github/MainClass.py", line 324, in get_repo
    headers, data = self.__requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 317, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.8/site-packages/github/Requester.py", line 342, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/repos#get-a-repository"}
```

**Comment by anmol098** [comment]
@itsnebulalol please do add github personal access token with repo and user access to repo secrets get the stats working
Then it will not get 404 error

**Comment by itsnebulalol** [comment]
Now I'm getting a 401 error, I'm running the workflow in my profile repository, which automatically puts the secret. Do I need to put it in manually?

The error is:
```
Traceback (most recent call last):
19
Exception Occurred Query failed to run by returning code of 401. 
20
{
21
    viewer {
22
      login
23
      id
24
    }
25
  }
26

27
  File "/main.py", line 491, in <module>
28
    user_data = run_query(userInfoQuery)  # Execute the query
29
  File "/main.py", line 152, in run_query
30
    raise Exception("Query failed to run by returning code of {}. {}".format(request.status_code, query))
31
Exception: Query failed to run by returning code of 401. 
32
{
33
    viewer {
34
      login
35
      id
36
    }
37
  }

```

**Comment by itsnebulalol** [comment]
Ok, I finally got it to work, I had to manually add the token as a secret.
